FROM node:20.19.6-alpine as builder

RUN apk add --no-cache openssl

WORKDIR /app
COPY ./package*.json ./
COPY yarn.lock ./

# Add prisma schema
COPY ./prisma ./prisma

RUN yarn

COPY . .

RUN npx prisma generate

CMD [ "yarn", "start:seed:studio:dev" ]