version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    image: petercbu/3p-booking-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3334:3334'
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
    name: nest-db
